export const LOG_IN = "LOG_IN"

export const LOG_OUT = "LOG_OUT"

export const SET_FORM_ERROR = "SET_FORM_ERROR"

export const RESET_FORM_ERROR = "RESET_FORM_ERROR"

export const SET_FORM_ERROR_MESSAGE = "SET_FORM_ERROR_MESSAGE"

export const RESET_FORM_ERROR_MESSAGE = "RESET_FORM_ERROR_MESSAGE"

export const SET_USER = "SET_USER"

export const RESET_USER = "RESET_USER"

export const SET_SHOW_SPLASH_SCREEN = "SET_SHOW_SPLASH_SCREEN"

export const RESET_SHOW_SPLASH_SCREEN = "RESET_SHOW_SPLASH_SCREEN"
